# Generated by Django 3.0.3 on 2020-12-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigs1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
